### ISSUE TITLE
Journalists

### ISSUE THREAD

**Issue by zaiyijiang** [Hoojeong/Team3#2]
As a journalist,
I want to gain some quick insights into what people in both countries value/care about on a wide range of topics.
So that I can tell stories of human interest that are interesting and creative.

Definition of done

We run a site that provides clear/professional/insightful knowledge of the differences and similarities between Chinese and American people.

Tasks
1. We make the visualization both clear and creative.
2. We offer relevant topics that are intriguing to journalists reporting on US-China relations.

**Comment by hdcameron** [comment]
Thanks Zhaiyi - this is great! 

I've been trying to build on your good work by scoping down a little further.  After some though, I believe that journalists would more likely  use the data we are presenting to complement other stories they are working on, rather then writing a story based on the data itself.  For example, if a journalist is writing on US-China competition and the World Health Organization, the journalist could refer to the level of confidence Chinese and Americans have in that institution.

Below is where I got with user stories about a journalist user.  I still need to do the INVEST, definition of done and tasks part... what do you think?

**Persona: John the American journalist** 

> _As a journalist in the US writing on international affairs…_

1. > I want evidence-based comparisons between Americans and Chinese views on key social, government and international issues so that I can refer to them with confidence to add depth to my stories about developments in the US-China relationship.
2. > I want easy access to many aspects of American and Chinese thinking so that I can glean quick insights without investing hours of research given tight publishing deadlines.
3. > I want to have confidence that the research was done with rigor so that my readers see my articles as credible and informative.

**Comment by zaiyijiang** [comment]
This is fantastic!!

**Comment by hdcameron** [comment]
I have moved my three sub-stories about John the American journalist to make three individual issues: #13, #14 and #15.

**Comment by hdcameron** [comment]
@zaiyijiang I hope you don't mind that I added your user story as a note in the backlog and closed this issue so that we can go through the process of choosing user stories that become issues in the story time meeting.
